### Get all credentials
GET http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}

### Get single credential
GET http://localhost:3000/api/credentials/Hamburg
Authorization: {{$dotenv MASTERPASSWORD}}

### Add single credential
POST http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}
Content-Type: application/json

{
    "service": "Hamburg",
    "username": "Ben",
    "password": "123456789"
}

### Delete single credential
DELETE http://localhost:3000/api/credentials/Hamburg
Authorization: {{$dotenv MASTERPASSWORD}}

### Replace existing credential
PUT http://localhost:3000/api/credentials/Hamburg
Authorization: {{$dotenv MASTERPASSWORD}}
Content-Type: application/json

{
    "service": "Dummi",
    "username": "Ben",
    "password": "12345678"
}